const movies = [
  {
    id: 1,
    title: "Interstellar",
    rating: "PG-13",
    image: "movie posters/posters/movie 1.jpg",
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E?si=N1-ioabJmkskKGGP",
    genre: "Science Fiction, Drama",
    director: "Christopher Nolan",
    duration: "2h 49m",
    releaseDate: "7 November 2014",
    cast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Michael Caine",
    language: "English",
    subtitles: "Arabic",
    description:
      "With humanity teetering on the brink of extinction, a group of astronauts travels through a wormhole in search of another inhabitable planet.",
  },
  {
    id: 2,
    title: "Se7en",
    rating: "R",
    image: "movie posters/posters/movie 2.jpg",
    trailer: "https://www.youtube.com/embed/znmZoVkCjpI?si=Vj2hQfKLA9EboqfO",
    genre: "Thriller,Crime",
    director: "David Fincher",
    duration: "2h 7m",
    releaseDate: "September 22, 1995",
    cast: "Brad Pitt and Morgan Freeman, with Gwyneth Paltrow and John C. McGinley in supporting roles.",
    language: "English",
    subtitles: "Arabic",
    description:
      "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
  },

  {
    id: 3,
    title: "The Shawshank Redemption",
    rating: "R",
    image: "movie posters/posters/movie 2.jpg",
    trailer: "https://www.youtube.com/embed/6hB3S9bIaco?si=Zb1Kl-LDkpTeNUHZ",
    genre: "Drama",
    director: "Frank Darabont",
    duration: "2h 22m",
    releaseDate: "14 October 1994",
    cast: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler, Clancy Brown, Gil Bellows",
    language: "English",
    subtitles: "Arabic",
    description:
      "Andy Dufresne, a banker wrongly convicted of murder, forms a friendship with Red, an inmate, and seeks redemption through hope, patience, and an unbreakable will.",
  },

  {
    id: 4,
    title: "Black Swan",
    rating: "R",
    image: "movie posters/posters/movie 3.jpg",
    trailer: "https://www.youtube.com/embed/5ja1Q5Z8Z6c?si=yZy2PWhNc-Xl38Xj",
    genre: "Drama, Thriller",
    director: "Darren Aronofsky",
    duration: "1h 48m",
    releaseDate: "17 December 2010",
    cast: "Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey, Winona Ryder",
    language: "English",
    subtitles: "Arabic",
    description:
      "A talented dancer struggles to maintain her mental health and her place in the lead role of a New York City ballet production, as she descends into a nightmarish world of obsession and delusion.",
  },

  {
    id: 5,
    title: "Howl's Moving Castle",
    rating: "PG",
    image: "movie posters/posters/movie 4.jpg",
    trailer: "https://www.youtube.com/embed/HiHi6csJc8A?si=azVn3ybIenWoSvhL",
    genre: "Animation, Fantasy",
    director: "Hayao Miyazaki",
    duration: "1h 59m",
    releaseDate: "20 November 2004",
    cast: "Chieko Baisho, Tatsuya Gashuin, Akihiro Miwa, Haruko Katô",
    language: "Japanese",
    subtitles: "English",
    description:
      "When a young woman is cursed by a witch, she transforms into an elderly woman and seeks refuge in a mysterious moving castle, where she meets a reclusive wizard and embarks on an extraordinary journey.",
  },

  {
    id: 6,
    title: "Inception",
    rating: "PG-13",
    image: "movie posters/posters/movie 5.jpg",
    trailer: "https://www.youtube.com/embed/8hP9D6kZseM?si=TPzEziP3hz5BR7QH",
    genre: "Action, Science Fiction",
    director: "Christopher Nolan",
    duration: "2h 28m",
    releaseDate: "16 July 2010",
    cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Cillian Murphy, Marion Cotillard",
    language: "English",
    subtitles: "Arabic",
    description:
      "A skilled thief is tasked with planting an idea into the mind of a CEO through the use of dream manipulation, leading to an action-packed, mind-bending heist across multiple dream layers.",
  },

  {
    id: 7,
    title: "Blade Runner 2049",
    rating: "R",
    image: "movie posters/posters/movie 6.jpg",
    trailer: "https://www.youtube.com/embed/gCcx85zbxz4?si=MTmYwLfqqg9e1A5J",
    genre: "Science Fiction, Thriller",
    director: "Denis Villeneuve",
    duration: "2h 44m",
    releaseDate: "6 October 2017",
    cast: "Ryan Gosling, Harrison Ford, Ana de Armas, Jared Leto, Robin Wright, Dave Bautista",
    language: "English",
    subtitles: "Arabic",
    description:
      "A young blade runner uncovers a long-buried secret that could reshape society, leading him on a journey to find Rick Deckard, a former blade runner who has been missing for three decades.",
  },

  {
    id: 8,
    title: "Shutter Island",
    rating: "R",
    image: "movie posters/posters/movie 7.jpg",
    trailer: "https://www.youtube.com/embed/5iaYLCiq5RM?si=avhTLVfH1CZoZeqo",
    genre: "Mystery, Thriller",
    director: "Martin Scorsese",
    duration: "2h 18m",
    releaseDate: "19 February 2010",
    cast: "Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley, Michelle Williams, Max von Sydow, Patricia Clarkson",
    language: "English",
    subtitles: "Arabic",
    description:
      "A U.S. Marshal investigates the disappearance of a prisoner from a mental institution located on a remote island, leading to a psychological journey filled with twists and dark revelations.",
  },

  {
    id: 9,
    title: "Deadpool & Wolverine",
    rating: "R",
    image: "movie posters/posters/movie 16.jpg",
    trailer: "https://www.youtube.com/embed/73_1biulkYk?si=AC2nalR-3tjhp5Jv",
    genre: "Action, Comedy, Superhero",
    director: "Shawn Levy",
    duration: "2h 8m",
    releaseDate: "July 22, 2024",
    cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin, Morena Baccarin, Rob Delaney, Leslie Uggams, Aaron Stanford, Matthew Macfadyen",
    language: "English",
    subtitles: "Arabic",
    description:
      "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
  },

  {
    id: 10,
    title: "Late Night in Solo",
    rating: "PG-13",
    image: "movie posters/posters/movie 10.jpg",
    trailer: "https://www.youtube.com/embed/xyz?si=abc",
    genre: "Comedy, Drama",
    director: "Nisha Ganatra",
    duration: "1h 42m",
    releaseDate: "7 June 2019",
    cast: "Emma Thompson, Mindy Kaling, John Lithgow, Hugh Dancy, Reid Scott",
    language: "English",
    subtitles: "Arabic",
    description:
      "A late-night talk show host hires a diverse new writer to spice up her show, which sparks a series of unexpected revelations and comedic moments.",
  },

  {
    id: 11,
    title: "Inglourious Basterds",
    rating: "R",
    image: "movie posters/posters/movie 11.jpg",
    trailer: "https://www.youtube.com/embed/KnrRy6kSFF0?si=yGQ2l_gVdPzyqpnb",
    genre: "Adventure, Drama, War",
    director: "Quentin Tarantino",
    duration: "2h 33m",
    releaseDate: "21 August 2009",
    cast: "Brad Pitt, Christoph Waltz, Mélanie Laurent, Eli Roth, Michael Fassbender",
    language: "English, German, French",
    subtitles: "Arabic",
    description:
      "A group of Jewish-American soldiers plot to assassinate Nazi leaders during World War II, while a French Jewish theater owner seeks revenge on those who destroyed her family.",
  },

  {
    id: 12,
    title: "Atonement",
    rating: "R",
    image: "movie posters/posters/movie 12.jpg",
    trailer: "https://www.youtube.com/embed/AJPz5aNnl2o?si=kj02Q3Vo1gT0yn2V",
    genre: "Drama, Romance, War",
    director: "Joe Wright",
    duration: "2h 3m",
    releaseDate: "7 September 2007",
    cast: "James McAvoy, Keira Knightley, Saoirse Ronan, Romola Garai, Benedict Cumberbatch",
    language: "English",
    subtitles: "Arabic",
    description:
      "A young girl makes a false accusation that changes the lives of two lovers, leading to a series of events that unfold over the years during World War II.",
  },

  {
    id: 13,
    title: "Memories of Murder",
    rating: "R",
    image: "movie posters/posters/movie 13.jpg",
    trailer: "https://www.youtube.com/embed/7Pq1SzjYYNY?si=wXZ7_Y3Rbd9fK67Y",
    genre: "Crime, Drama, Mystery",
    director: "Bong Joon-ho",
    duration: "2h 12m",
    releaseDate: "24 April 2003",
    cast: "Song Kang-ho, Kim Sang-kyung, Park Hae-il, Kim Roi-ha",
    language: "Korean",
    subtitles: "Arabic",
    description:
      "In 1986, two detectives investigate a series of brutal murders in a small Korean province, uncovering disturbing truths and facing frustrating barriers in their pursuit of the killer.",
  },

  {
    id: 14,
    title: "Pulp Fiction",
    rating: "R",
    image: "movie posters/posters/movie 14.jpg",
    trailer: "https://www.youtube.com/embed/s7EdQ4FqbhY?si=X3J_TAf8qv6cfyO7",
    genre: "Crime, Drama",
    director: "Quentin Tarantino",
    duration: "2h 34m",
    releaseDate: "14 October 1994",
    cast: "John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis, Harvey Keitel, Tim Roth",
    language: "English",
    subtitles: "Arabic",
    description:
      "The lives of several characters intertwine in a series of stories involving crime, revenge, and redemption in Los Angeles, told in a nonlinear narrative.",
  },

  {
    id: 15,
    title: "Your Name",
    rating: "PG",
    image: "movie posters/posters/movie 15.jpg",
    trailer: "https://www.youtube.com/embed/yo3Q8hd9LZw?si=rfSvhDF4chhlr1OJ",
    genre: "Animation, Drama, Romance",
    director: "Makoto Shinkai",
    duration: "1h 46m",
    releaseDate: "3 August 2016",
    cast: "Ryûnosuke Kamiki, Mone Kamishiraishi, Natsuki Hanae, Etsuko Ichihara",
    language: "Japanese",
    subtitles: "English",
    description:
      "Two teenagers, a boy and a girl, inexplicably begin to swap bodies, and as they navigate each other's lives, they develop a deep connection that spans time and space.",
  },
];
